# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - bug
    - title: 🛠️ Bug Fix
      labels:
        - bug
    - title: 📦 Dependencies
      labels:
        - dependencies
        
